### ISSUE TITLE
Overwrite existing comment instead of a new comment for each new commit

### ISSUE THREAD

**Issue by kdheepak** [1Password/check-signed-commits-action#8]
Thanks for making this action!

If I make a PR and make multiple commits without signing, this action runs on every commit and posts multiple github comments which makes the PR quite noisy.

Would it be possible to overwrite or update an existing comment instead?

**Comment by florisvdg** [comment]
Just to confirm: You're seeing multiple comments per _push_, right? Not multiple comments in succession for different commits in a single push?

What I could do is have the action fetch the latest PR comments and if it finds that the comment was posted already, not post it again.

**Comment by kdheepak** [comment]
Yes, you are right, it is subsequent pushes. That solution would work great!

**Comment by florisvdg** [comment]
@kdheepak The change got released in [v1.2.0](https://github.com/1Password/check-signed-commits-action/releases/tag/v1.2.0) and can be used in a workflow using `@v1.2.0` or `@v1`. Thanks for reporting!

**Comment by kdheepak** [comment]
Thank you!
